### PR TITLE
descendants method fixed

### PR DESCRIPTION
**Pull request by tchukuchuk**
I've fixed descendants method which doesn't work for me if self.instance_variable_get(:@new_record) returns nil and not false.

### CODE REVIEW

**Comment by saks** [comment]
Can you provide some more info? 
This workaround was to return empty array for models that haven't @new_record variable. Your patch breaks this behavior and if @new_record is nil (i.e. model not fully initialized yet) plugin will try to find it's descendants.

**Comment by tchukuchuk** [comment]
here is my issue :
https://gist.github.com/740709

**Comment by saks** [comment]
Thanks a lot. I'll check this and find solution.

**Comment by saks** [comment]
This strange behavior of mongoid was already fixed in [this](https://github.com/mongoid/mongoid/commit/3030da59) commit so i will revert [this](https://github.com/saks/mongoid_acts_as_tree/commit/0268fb1997d07d04b51ffb8dda670ab28ebc717f) commit.

I've checked your gist and it looks like there is no any issues.

Thank you for help!

**Pull request closed without merging**
